spring.application.name=passwordManager

spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.data.redis.url=${REDIS_URL}

langchain4j.google-ai-gemini.chat-model.api-key=${GEMINI_TOKEN}
langchain4j.google-ai-gemini.chat-model.model-name=gemini-2.5-flash-lite

app.jwt.secret=${JWT_SECRET_KEY}
app.jwt.expiration=86400000
app.encryption.key=${ENCRYPTION_KEY}

logging.level.com.shk.personalProject=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=trace

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs